### ISSUE TITLE
macOS build broken with Zig 0.16.0-dev - TargetConditionals.h compatibility issue

### ISSUE THREAD

**Issue by jawa0** [jawa0/zig_sdl_gui#1]
## Problem

Building on macOS with Zig 0.16.0-dev fails during C import of SDL headers due to macOS SDK compatibility issues.

## Environment

- **OS**: macOS 13.2 Ventura
- **Xcode SDK**: MacOSX13.3.sdk
- **Zig version**: 0.16.0-dev.2261+d6b3dd25a
- **Architecture**: x86_64 (Intel Mac)
- **Homebrew**: SDL2 and SDL2_ttf installed at `/usr/local`

## Error

```
src/sdl.zig:4:15: error: C import failed
pub const c = @cImport({
              ^~~~~~~~

error: translation failure
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/TargetConditionals.h:487:10:
error: TargetConditionals.h: unknown compiler (see comment above)
        #error TargetConditionals.h: unknown compiler (see comment above)
         ^
```

## Root Cause

The macOS SDK header `TargetConditionals.h` does not recognize Zig's compiler and fails with "unknown compiler" error during `@cImport` of SDL headers.

## Attempted Workarounds

1. **Build system C macros** - Added `-D__clang__=1` to build flags (doesn't affect `@cImport`)
2. **@cDefine in @cImport** - Defined `__clang__`, `__clang_major__`, `__clang_minor__`, `__clang_patchlevel__` inside `@cImport` block
3. **Added __GNUC__ defines** - Also defined `__GNUC__`, `__GNUC_MINOR__`, `__GNUC_PATCHLEVEL__`

None of these workarounds resolved the issue.

## Current Status

macOS build is documented as broken in CLAUDE.md. Windows and Linux builds work correctly with Zig 0.15.2.

## Possible Solutions

- Wait for Zig 0.16+ to improve macOS SDK compatibility
- Try with a different/newer Xcode SDK version
- Investigate if there are additional compiler identification macros needed
- Consider using pkg-config instead of manual paths for SDL discovery
